version: '3.9'
services:
  postgres:
    container_name: postgres-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment: # Only used on local dev machine
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookdb
    ports:
      - "5432:5432"